#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
export PYTHONPATH="${DIR}/tui/src:${PYTHONPATH}"
exec "${DIR}/tui/.venv/bin/python" "${DIR}/tui/src/main.py" "$@"